title: Nick Mooney
email: nmooney@cs.washington.edu
description: >-
  Security and summer camp (but not at the same time).
baseurl: ""
url: "https://nickmooney.com"
enforce_ssl: nickmooney.com
show_excerpts: true

# Social links
twitter_username: wellhydrated
linkedin_username: nick-mooney-6633bb149
github_username:  nickmooney

# Commenting, analytics
disqus:
  shortname: nick-mooney
google_analytics: UA-87475309-1

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME

