baseURL = "https://nickmooney.com"
languageCode = "en-us"
title = "Nick Mooney"
theme = "xmin"

[permalinks]
  post = ':slug/'

[menu]
[[menu.main]]
  identifier = 'main'
  name = 'Main'
  url = ''
  weight = -110

[params]
  footer = "&copy; [Nick Mooney](https://nickmooney.com) 2016 -- {Year} | [Twitter](https://twitter.com/wellhydrated) | [Mastodon](https://hachyderm.io/@wellhydrated)"